spring:
  application:
    name: reservation-system
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
